using Dip.Domain.Enums;

namespace Dip.Infrastructure.Seeding;

// Every list in the Picklists workbook (samples/PickLists.xlsx, sheet Pick_Lists), generated from
// the workbook on 2026-09-08 so a fresh database has dropdown values before the first Drive poll.
// The poll and the PicklistImporter upsert over these rows by (Field, Code); refactor-plan § 7.
internal static class SeedPicklists
{
    public static IReadOnlyList<(PicklistField Field, string Code, string Description)> Items { get; } =
    [
        // Project (1)
        (PicklistField.Project, "QF01012", "Qiddaya Performing Arts Center"),
        // Originator (1)
        (PicklistField.Originator, "NES", "Nesma and Partners"),
        // Contract (1)
        (PicklistField.Contract, "C04518", "Contract Number"),
        // DocType (94)
        (PicklistField.DocType, "AGD", "Agenda"),
        (PicklistField.DocType, "AVV", "Agreed Value of Variation"),
        (PicklistField.DocType, "ASB", "As Built"),
        (PicklistField.DocType, "AUR", "Audit Report"),
        (PicklistField.DocType, "BOQ", "Bill of Quantities"),
        (PicklistField.DocType, "BEP", "BIM Execution Plan"),
        (PicklistField.DocType, "BIM", "BIM Model"),
        (PicklistField.DocType, "BRF", "Brief"),
        (PicklistField.DocType, "BUD", "Budget"),
        (PicklistField.DocType, "CAL", "Calculation"),
        (PicklistField.DocType, "CER", "Certificate"),
        (PicklistField.DocType, "COR", "Change Order"),
        (PicklistField.DocType, "CRA", "Change Request Authorization"),
        (PicklistField.DocType, "CDT", "Clash Detection Report"),
        (PicklistField.DocType, "CLM", "Claim"),
        (PicklistField.DocType, "CIN", "Client Instruction"),
        (PicklistField.DocType, "CRS", "Comments Resolution Sheet"),
        (PicklistField.DocType, "CON", "Contract"),
        (PicklistField.DocType, "COS", "Cost Estimate"),
        (PicklistField.DocType, "DAB", "Dashboard"),
        (PicklistField.DocType, "DOA", "Delegation of Authority"),
        (PicklistField.DocType, "DES", "Design"),
        (PicklistField.DocType, "MTX", "Distribution Matrix"),
        (PicklistField.DocType, "DSS", "Dossier"),
        (PicklistField.DocType, "DRW", "Drawing"),
        (PicklistField.DocType, "ENI", "Engineer Instruction"),
        (PicklistField.DocType, "EXP", "Expenses"),
        (PicklistField.DocType, "HOC", "Handover Certificate"),
        (PicklistField.DocType, "IRT", "Incident Report"),
        (PicklistField.DocType, "ITP", "Inspection & Test Plan"),
        (PicklistField.DocType, "INS", "Instruction"),
        (PicklistField.DocType, "IAB", "Insurance and Bonds"),
        (PicklistField.DocType, "INV", "Invoice"),
        (PicklistField.DocType, "LAR", "Laydown Area Access Request"),
        (PicklistField.DocType, "LTR", "Letter"),
        (PicklistField.DocType, "LIC", "License"),
        (PicklistField.DocType, "LST", "List"),
        (PicklistField.DocType, "MAN", "Manual"),
        (PicklistField.DocType, "MPL", "Master Plan"),
        (PicklistField.DocType, "MAR", "Material Approval Request"),
        (PicklistField.DocType, "MIR", "Material Inspection Request"),
        (PicklistField.DocType, "MST", "Method Statement"),
        (PicklistField.DocType, "MOM", "Minutes of Meeting"),
        (PicklistField.DocType, "MIX", "Mix Design"),
        (PicklistField.DocType, "MOD", "Model"),
        (PicklistField.DocType, "MRP", "Monthly Report"),
        (PicklistField.DocType, "NOC", "No Objection Certificate"),
        (PicklistField.DocType, "NCR", "Non-Conformance Report"),
        (PicklistField.DocType, "NDA", "Non-Disclosure Agreement"),
        (PicklistField.DocType, "NTC", "Notice"),
        (PicklistField.DocType, "OMM", "Operation & Maintenance Manual"),
        (PicklistField.DocType, "ORC", "Organizational Chart"),
        (PicklistField.DocType, "OTR", "Overtime Request"),
        (PicklistField.DocType, "PAP", "Payment Application"),
        (PicklistField.DocType, "PYC", "Payment Certificate"),
        (PicklistField.DocType, "PRM", "Permit"),
        (PicklistField.DocType, "PAF", "Personnel Approval Form"),
        (PicklistField.DocType, "PIV", "Photographs, Images & Videos"),
        (PicklistField.DocType, "PLN", "Plan"),
        (PicklistField.DocType, "PLT", "Plant"),
        (PicklistField.DocType, "PPG", "Policy & Procedure"),
        (PicklistField.DocType, "PQS", "Prequalification Submittal"),
        (PicklistField.DocType, "PRE", "Presentation"),
        (PicklistField.DocType, "PRO", "Procedure"),
        (PicklistField.DocType, "PEP", "Project Execution Plan"),
        (PicklistField.DocType, "PRS", "Proposal"),
        (PicklistField.DocType, "POR", "Purchase Order"),
        (PicklistField.DocType, "REG", "Register"),
        (PicklistField.DocType, "REP", "Report"),
        (PicklistField.DocType, "RFC", "Request For Change"),
        (PicklistField.DocType, "RSM", "Resume"),
        (PicklistField.DocType, "SVR", "Safety Violation Report"),
        (PicklistField.DocType, "SMP", "Sample"),
        (PicklistField.DocType, "SCH", "Schedule"),
        (PicklistField.DocType, "SDW", "Shop Drawing"),
        (PicklistField.DocType, "SIN", "Site Instruction"),
        (PicklistField.DocType, "SOR", "Site Observation Report"),
        (PicklistField.DocType, "SPE", "Specification"),
        (PicklistField.DocType, "STD", "Standard"),
        (PicklistField.DocType, "SFA", "Statement of Final Account"),
        (PicklistField.DocType, "STR", "Strategy"),
        (PicklistField.DocType, "TOC", "Taking Over Certificate"),
        (PicklistField.DocType, "TOR", "Task Order"),
        (PicklistField.DocType, "TEM", "Template"),
        (PicklistField.DocType, "TDC", "Tender Document"),
        (PicklistField.DocType, "TRP", "Test Report"),
        (PicklistField.DocType, "TMS", "Time Sheet"),
        (PicklistField.DocType, "VOR", "Variation Order"),
        (PicklistField.DocType, "WAR", "Warranty / Guarantees"),
        (PicklistField.DocType, "WRP", "Weekly Report"),
        (PicklistField.DocType, "WIR", "Work Inspection Request"),
        (PicklistField.DocType, "RLM", "RedLine Mark Drawing"),
        (PicklistField.DocType, "MDP", "Master Information Delivery Plan"),
        (PicklistField.DocType, "TDP", "Task Information Delivery Plan"),
        // Discipline (98)
        (PicklistField.Discipline, "ACO", "Acoustic"),
        (PicklistField.Discipline, "ADM", "Administration"),
        (PicklistField.Discipline, "ARC", "Architectural"),
        (PicklistField.Discipline, "ADT", "Area Development"),
        (PicklistField.Discipline, "ASM", "Assets Management"),
        (PicklistField.Discipline, "AVL", "Audio Visual"),
        (PicklistField.Discipline, "AUV", "Audio/Video"),
        (PicklistField.Discipline, "BRG", "Bridges"),
        (PicklistField.Discipline, "BRC", "Broadcast"),
        (PicklistField.Discipline, "BIM", "Building Information Modelling"),
        (PicklistField.Discipline, "BMS", "Building Management System"),
        (PicklistField.Discipline, "CWC", "Chilled Water / Cooling"),
        (PicklistField.Discipline, "CIV", "Civil"),
        (PicklistField.Discipline, "CPM", "Contracts & Procurement"),
        (PicklistField.Discipline, "CIN", "Controls & Instrumentation"),
        (PicklistField.Discipline, "CRE", "Creative Designer"),
        (PicklistField.Discipline, "CDM", "Crowd Management"),
        (PicklistField.Discipline, "CUL", "Culvert"),
        (PicklistField.Discipline, "DRN", "Drainage"),
        (PicklistField.Discipline, "ELP", "Earthing & Lighting Protection"),
        (PicklistField.Discipline, "ELE", "Electrical"),
        (PicklistField.Discipline, "ELC", "Electrical Containment"),
        (PicklistField.Discipline, "ENV", "Environmental"),
        (PicklistField.Discipline, "EQP", "Equipment"),
        (PicklistField.Discipline, "FAC", "Facade"),
        (PicklistField.Discipline, "FED", "Federated"),
        (PicklistField.Discipline, "FIN", "Finance"),
        (PicklistField.Discipline, "FAE", "Fire Alarm & Emergency Lighting"),
        (PicklistField.Discipline, "FLS", "Fire Life Safety"),
        (PicklistField.Discipline, "FPR", "Fire Protection"),
        (PicklistField.Discipline, "FFE", "Furniture Fixture & Equipment"),
        (PicklistField.Discipline, "GEN", "General"),
        (PicklistField.Discipline, "GIS", "Geospatial Information System"),
        (PicklistField.Discipline, "GEH", "Geotechnical & Hydraulics"),
        (PicklistField.Discipline, "GRA", "Graphics"),
        (PicklistField.Discipline, "HSE", "Health and Safety"),
        (PicklistField.Discipline, "EHV", "High Voltage"),
        (PicklistField.Discipline, "HVC", "HVAC"),
        (PicklistField.Discipline, "ICT", "Information & Communication Technology"),
        (PicklistField.Discipline, "INF", "Infrastructure"),
        (PicklistField.Discipline, "INS", "Installation"),
        (PicklistField.Discipline, "ITS", "Intelligent Transportation System"),
        (PicklistField.Discipline, "INT", "Interior Design"),
        (PicklistField.Discipline, "IRR", "Irrigation"),
        (PicklistField.Discipline, "KNL", "Kitchen & Laundry"),
        (PicklistField.Discipline, "LSE", "Landscape"),
        (PicklistField.Discipline, "ELL", "Lighting"),
        (PicklistField.Discipline, "LTC", "Lighting Control"),
        (PicklistField.Discipline, "ELV", "Low Voltage"),
        (PicklistField.Discipline, "LPG", "LPG"),
        (PicklistField.Discipline, "MAR", "Marine Engineering"),
        (PicklistField.Discipline, "MPL", "Master Planning"),
        (PicklistField.Discipline, "MEC", "Mechanical"),
        (PicklistField.Discipline, "EMV", "Medium Voltage"),
        (PicklistField.Discipline, "MEP", "MEPF"),
        (PicklistField.Discipline, "NTD", "Non-Technical Document"),
        (PicklistField.Discipline, "OSE", "Operating Supplies and Equipment"),
        (PicklistField.Discipline, "OTH", "Others"),
        (PicklistField.Discipline, "PLB", "Plumbing"),
        (PicklistField.Discipline, "PTW", "Potable Water"),
        (PicklistField.Discipline, "PJC", "Project Control"),
        (PicklistField.Discipline, "QMS", "Quality Management"),
        (PicklistField.Discipline, "RID", "Rides"),
        (PicklistField.Discipline, "ERL", "Road Lighting"),
        (PicklistField.Discipline, "RKW", "Rockwork"),
        (PicklistField.Discipline, "SEC", "Security System"),
        (PicklistField.Discipline, "SEW", "Sewage"),
        (PicklistField.Discipline, "SHW", "Show"),
        (PicklistField.Discipline, "SGN", "Signage / Wayfinding"),
        (PicklistField.Discipline, "ESP", "Small Power"),
        (PicklistField.Discipline, "SSC", "Smart City"),
        (PicklistField.Discipline, "SPL", "Specialist Lighting"),
        (PicklistField.Discipline, "SWD", "Storm Water Drainage"),
        (PicklistField.Discipline, "STR", "Structural"),
        (PicklistField.Discipline, "SUR", "Surveying / Mapping"),
        (PicklistField.Discipline, "SUS", "Sustainability"),
        (PicklistField.Discipline, "TEL", "Telecommunication"),
        (PicklistField.Discipline, "TNC", "Testing/Commissioning"),
        (PicklistField.Discipline, "TFC", "Traffic System"),
        (PicklistField.Discipline, "UTI", "Utilities"),
        (PicklistField.Discipline, "VNT", "Ventilation Ductwork"),
        (PicklistField.Discipline, "VTR", "Vertical Transportation"),
        (PicklistField.Discipline, "VES", "Voice Evacuation"),
        (PicklistField.Discipline, "WSM", "Waste Management"),
        (PicklistField.Discipline, "WTR", "Water"),
        (PicklistField.Discipline, "CTV", "CCTV System"),
        (PicklistField.Discipline, "ACS", "Access Control System"),
        (PicklistField.Discipline, "EFL", "Facade Lighting"),
        (PicklistField.Discipline, "DES", "Diesel"),
        (PicklistField.Discipline, "SMK", "Smoke Ductwork"),
        (PicklistField.Discipline, "STL", "Steel Structure"),
        (PicklistField.Discipline, "FWR", "Formwork"),
        (PicklistField.Discipline, "ELS", "Emergency Lighting system"),
        (PicklistField.Discipline, "EBW", "Electrical Builder Works"),
        (PicklistField.Discipline, "MBW", "Mechanical Builder Works"),
        (PicklistField.Discipline, "EBC", "Electrical Busway"),
        (PicklistField.Discipline, "WFT", "Water Features"),
        (PicklistField.Discipline, "LOG", "Logistics"),
        // Zone (29)
        (PicklistField.Zone, "00", "Overall"),
        (PicklistField.Zone, "01", "Zone Sheet 1"),
        (PicklistField.Zone, "02", "Zone Sheet 2"),
        (PicklistField.Zone, "03", "Zone Sheet 3"),
        (PicklistField.Zone, "04", "Zone Sheet 4"),
        (PicklistField.Zone, "05", "Zone Sheet 5"),
        (PicklistField.Zone, "06", "Zone Sheet 6"),
        (PicklistField.Zone, "07", "Zone Sheet 7"),
        (PicklistField.Zone, "08", "Zone Sheet 8"),
        (PicklistField.Zone, "09", "Zone Sheet 9"),
        (PicklistField.Zone, "10", "Zone Sheet 10"),
        (PicklistField.Zone, "11", "Zone Sheet 11"),
        (PicklistField.Zone, "12", "Zone Sheet 12"),
        (PicklistField.Zone, "13", "Zone Sheet 13"),
        (PicklistField.Zone, "14", "Zone Sheet 14"),
        (PicklistField.Zone, "15", "Zone Sheet 15"),
        (PicklistField.Zone, "16", "Zone Sheet 16"),
        (PicklistField.Zone, "17", "Zone Sheet 17"),
        (PicklistField.Zone, "18", "Zone Sheet 18"),
        (PicklistField.Zone, "19", "Zone Sheet 19"),
        (PicklistField.Zone, "20", "Zone Sheet 20"),
        (PicklistField.Zone, "21", "Zone Sheet 21"),
        (PicklistField.Zone, "22", "Zone Sheet 22"),
        (PicklistField.Zone, "23", "Zone Sheet 23"),
        (PicklistField.Zone, "24", "Zone Sheet 24"),
        (PicklistField.Zone, "25", "Zone Sheet 25"),
        (PicklistField.Zone, "26", "Zone Sheet 26"),
        (PicklistField.Zone, "27", "Zone Sheet 27"),
        (PicklistField.Zone, "28", "Zone Sheet 28"),
        // Building (12)
        (PicklistField.Building, "Z00000", "Overall"),
        (PicklistField.Building, "CENT01", "Center Block"),
        (PicklistField.Building, "GARD01", "Guard House"),
        (PicklistField.Building, "BLAD01", "Blade 01"),
        (PicklistField.Building, "BLAD02", "Blade 02"),
        (PicklistField.Building, "BLAD03", "Blade 03"),
        (PicklistField.Building, "BLAD04", "Blade 04"),
        (PicklistField.Building, "BLAD05", "Blade 05"),
        (PicklistField.Building, "MBLAD1", "Mini Blade 01"),
        (PicklistField.Building, "MBLAD4", "Mini Blade 04"),
        (PicklistField.Building, "SECE01", "SEC Room"),
        (PicklistField.Building, "PARK01", "Parking Building"),
        // DrawingType (10)
        (PicklistField.DrawingType, "0", "General (General Notes, Abbreviations, Legends, Single Line Diagrams, General Detail)"),
        (PicklistField.DrawingType, "1", "Elevations (Vertical View)"),
        (PicklistField.DrawingType, "2", "Plans (Overall, Horizontal View, Floor Plan, Ceiling Plan, Site Plan, Loading Plan)"),
        (PicklistField.DrawingType, "3", "Sections (Sectional View, Wall Section, Riser)"),
        (PicklistField.DrawingType, "4", "Large-scale Views (Enlarged Details) (Plans, Elevations, Stair Sections, etc)"),
        (PicklistField.DrawingType, "5", "Details (Any detail view, such as Wall / Floor / Manhole Detail, etc)"),
        (PicklistField.DrawingType, "6", "Schedules and Diagrams"),
        (PicklistField.DrawingType, "7", "Combination of different views"),
        (PicklistField.DrawingType, "8", "User-Defined (For types that do not fall in other categories)"),
        (PicklistField.DrawingType, "9", "3D Representation (Isometric, Perspectives, Photographes)"),
        // Level (16)
        (PicklistField.Level, "00", "Non-Specific ( For Blade )"),
        (PicklistField.Level, "B1", "Basement 1 - Parking A +900.50"),
        (PicklistField.Level, "B2", "Basement 2 - Service +893.50"),
        (PicklistField.Level, "B3", "Basement 3 - Promenade +887.750"),
        (PicklistField.Level, "FL", "Foundation level"),
        (PicklistField.Level, "L1", "Lobby Level +905.0"),
        (PicklistField.Level, "L2", "Theater Stalls +913.0"),
        (PicklistField.Level, "L3", "Stalles Mezz & AD Theater +917.5"),
        (PicklistField.Level, "L4", "First Circle & AD Theater +921.0"),
        (PicklistField.Level, "L5", "Second Circle & Loft"),
        (PicklistField.Level, "L6", "SKY Garden +935.85"),
        (PicklistField.Level, "L8", "Royal Majlis +948.10M"),
        (PicklistField.Level, "M1", "Mez Upper Lobby +909.0"),
        (PicklistField.Level, "M2", "Mez Loft MEP  +931.10"),
        (PicklistField.Level, "RL", "Roof Level"),
        (PicklistField.Level, "ZZ", "Overall"),
        // AuthoringSoftware (13)
        (PicklistField.AuthoringSoftware, "Revit", ""),
        (PicklistField.AuthoringSoftware, "Civil3D", ""),
        (PicklistField.AuthoringSoftware, "MicrosoftWord", ""),
        (PicklistField.AuthoringSoftware, "MicrosoftExcel", ""),
        (PicklistField.AuthoringSoftware, "Navisworks", ""),
        (PicklistField.AuthoringSoftware, "inDesign", ""),
        (PicklistField.AuthoringSoftware, "Inviso", ""),
        (PicklistField.AuthoringSoftware, "JPG", ""),
        (PicklistField.AuthoringSoftware, "Recap", ""),
        (PicklistField.AuthoringSoftware, "Rhino", ""),
        (PicklistField.AuthoringSoftware, "Sketchup", ""),
        (PicklistField.AuthoringSoftware, "Autocad", ""),
        (PicklistField.AuthoringSoftware, "ArcGIS", ""),
        // ExchangeFormat (26)
        (PicklistField.ExchangeFormat, ".rvt", ""),
        (PicklistField.ExchangeFormat, ".nwc", ""),
        (PicklistField.ExchangeFormat, ".nwd", ""),
        (PicklistField.ExchangeFormat, ".ifc", ""),
        (PicklistField.ExchangeFormat, ".pdf", ""),
        (PicklistField.ExchangeFormat, ".jpg", ""),
        (PicklistField.ExchangeFormat, ".xls", ""),
        (PicklistField.ExchangeFormat, ".xer", ""),
        (PicklistField.ExchangeFormat, ".dwf", ""),
        (PicklistField.ExchangeFormat, ".dwg", ""),
        (PicklistField.ExchangeFormat, ".bcf", ""),
        (PicklistField.ExchangeFormat, ".3ds", ""),
        (PicklistField.ExchangeFormat, ".skp", ""),
        (PicklistField.ExchangeFormat, ".docx", ""),
        (PicklistField.ExchangeFormat, ".rvt,.nwd,.ifc", ""),
        (PicklistField.ExchangeFormat, ".nwc,.nwd,.ifc", ""),
        (PicklistField.ExchangeFormat, ".dwg,.nwc,.ifc", ""),
        (PicklistField.ExchangeFormat, ".docx,.pdf", ""),
        (PicklistField.ExchangeFormat, ".xer,.pdf", ""),
        (PicklistField.ExchangeFormat, ".xls,.pdf", ""),
        (PicklistField.ExchangeFormat, ".msp,.pdf", ""),
        (PicklistField.ExchangeFormat, ".dwg,.pdf", ""),
        (PicklistField.ExchangeFormat, ".indd", ""),
        (PicklistField.ExchangeFormat, ".pdf, .indd", ""),
        (PicklistField.ExchangeFormat, ".rvt,.nwc,.ifc", ""),
        (PicklistField.ExchangeFormat, ".gdb", ""),
        // ScopeArea (31)
        (PicklistField.ScopeArea, "Design Management", ""),
        (PicklistField.ScopeArea, "Architecture / LDC", ""),
        (PicklistField.ScopeArea, "Landscape", ""),
        (PicklistField.ScopeArea, "Interior Design", ""),
        (PicklistField.ScopeArea, "Signage & Wayfinding", ""),
        (PicklistField.ScopeArea, "Public Interaction & Activation", ""),
        (PicklistField.ScopeArea, "Structure", ""),
        (PicklistField.ScopeArea, "Geotechnical Engineering", ""),
        (PicklistField.ScopeArea, "Civil Engineering", ""),
        (PicklistField.ScopeArea, "MEP Engineering", ""),
        (PicklistField.ScopeArea, "Fire & Life Safety", ""),
        (PicklistField.ScopeArea, "Pitch Design & Sports Playing Surfaces", ""),
        (PicklistField.ScopeArea, "Specialist Lighting (Services and Systems)", ""),
        (PicklistField.ScopeArea, "Acoustics", ""),
        (PicklistField.ScopeArea, "AV / Broadcast", ""),
        (PicklistField.ScopeArea, "Security", ""),
        (PicklistField.ScopeArea, "Vertical Transport", ""),
        (PicklistField.ScopeArea, "Facade & Roof Envelope", ""),
        (PicklistField.ScopeArea, "Crowd Modelling / Pedestrian Flow", ""),
        (PicklistField.ScopeArea, "Sustainability", ""),
        (PicklistField.ScopeArea, "Accessibility", ""),
        (PicklistField.ScopeArea, "Architect of Record", ""),
        (PicklistField.ScopeArea, "Food & Beverage & Operations", ""),
        (PicklistField.ScopeArea, "Utilities, Roads & Infrastructure", ""),
        (PicklistField.ScopeArea, "Traffic & Car Parking", ""),
        (PicklistField.ScopeArea, "Technology (ICT)", ""),
        (PicklistField.ScopeArea, "Sports & Specialist Lighting", ""),
        (PicklistField.ScopeArea, "BMS & Access Control", ""),
        (PicklistField.ScopeArea, "Waste Management", ""),
        (PicklistField.ScopeArea, "Health & Safety in Design", ""),
        (PicklistField.ScopeArea, "Wind", ""),
        // SuitabilityCode (14)
        (PicklistField.SuitabilityCode, "S0 (WIP)", "Initial status or WIP"),
        (PicklistField.SuitabilityCode, "S1 (Shared)", "Suitable for Coordination"),
        (PicklistField.SuitabilityCode, "S2 (Shared)", "Suitable for Information"),
        (PicklistField.SuitabilityCode, "S3 (Shared)", "Suitable for Review and Comment"),
        (PicklistField.SuitabilityCode, "S4 (Shared)", "Suitable for Review and Authorisation"),
        (PicklistField.SuitabilityCode, "S5 (Shared)", "Suitable for Review and Acceptance"),
        (PicklistField.SuitabilityCode, "A1 (Published)", "Authorised and Accepted-Concept Design"),
        (PicklistField.SuitabilityCode, "A2 (Published)", "Authorised and Accepted-Schematic Design 100%"),
        (PicklistField.SuitabilityCode, "A3 (Published)", "Authorised and Accepted-Detailed Design 100%"),
        (PicklistField.SuitabilityCode, "A4 (Published)", "Authorised and Accepted-Tender"),
        (PicklistField.SuitabilityCode, "A5 (Published)", "Authorised and Accepted-IFC"),
        (PicklistField.SuitabilityCode, "A6 (Published)", "Authorised and Accepted-Construction (Shop Drawing)"),
        (PicklistField.SuitabilityCode, "A7 (Published)", "Authorised and Accepted-As Built"),
        (PicklistField.SuitabilityCode, "A8(Published)", "Authorised and Accepted-In Use"),
        // Scale (16)
        (PicklistField.Scale, "NTS", ""),
        (PicklistField.Scale, "AS INDICATED", ""),
        (PicklistField.Scale, "1:1", ""),
        (PicklistField.Scale, "1:2", ""),
        (PicklistField.Scale, "1:5", ""),
        (PicklistField.Scale, "1:10", ""),
        (PicklistField.Scale, "1:20", ""),
        (PicklistField.Scale, "1:25", ""),
        (PicklistField.Scale, "1:50", ""),
        (PicklistField.Scale, "1:100", ""),
        (PicklistField.Scale, "1:150", ""),
        (PicklistField.Scale, "1:200", ""),
        (PicklistField.Scale, "1:250", ""),
        (PicklistField.Scale, "1:300", ""),
        (PicklistField.Scale, "1:350", ""),
        (PicklistField.Scale, "1:500", ""),
        // Classification (10)
        (PicklistField.Classification, "FI_60_25", "Drawing"),
        (PicklistField.Classification, "FI_90_75", "Schedule or table"),
        (PicklistField.Classification, "FI_60_53", "Model"),
        (PicklistField.Classification, "FI_60_15", "Clash Rendition"),
        (PicklistField.Classification, "FI_40_10", "Calculations"),
        (PicklistField.Classification, "FI_90_72", "Report"),
        (PicklistField.Classification, "FI_10_90", "Transmittal"),
        (PicklistField.Classification, "FI_90_47", "Log"),
        (PicklistField.Classification, "FI_80_50", "Method statement"),
        (PicklistField.Classification, "FI_90_64", "Plan"),
        // CorporateDiscipline (9)
        (PicklistField.CorporateDiscipline, "Architectural", ""),
        (PicklistField.CorporateDiscipline, "Electrical", ""),
        (PicklistField.CorporateDiscipline, "Façade", ""),
        (PicklistField.CorporateDiscipline, "Fire & Life Safety", ""),
        (PicklistField.CorporateDiscipline, "Interior Design", ""),
        (PicklistField.CorporateDiscipline, "Infrastructure", ""),
        (PicklistField.CorporateDiscipline, "Landscape", ""),
        (PicklistField.CorporateDiscipline, "Mechanical", ""),
        (PicklistField.CorporateDiscipline, "Structural", ""),
        // Author (12)
        (PicklistField.Author, "Nesma & Partners", ""),
        (PicklistField.Author, "JINGGONG", ""),
        (PicklistField.Author, "ALUTEC", ""),
        (PicklistField.Author, "AFCO", ""),
        (PicklistField.Author, "DOKA", ""),
        (PicklistField.Author, "RAWABI", ""),
        (PicklistField.Author, "FALLPROTEC", ""),
        (PicklistField.Author, "TKE", ""),
        (PicklistField.Author, "Subcontractor - Unassigned", ""),
        (PicklistField.Author, "Provisional Sum", ""),
        (PicklistField.Author, "NAP PMO", ""),
        (PicklistField.Author, "Sana Al-Jazerah", ""),
    ];
}
